name: Branch validation

permissions:
  id-token: write
  contents: read

on:
  push:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'master' }}

jobs:
  safety:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: |
          sudo apt install krb5-multidev libkrb5-dev  krb5-config

      - uses: pypa/gh-action-pip-audit@v1.1.0
        with:
          inputs: constraints-2.10.3/constraints-3.11-dohop-3.txt
